[[guide]]
name = "Lorem"
weight = 10
identifier = "lorem"
url = "/guide/lorem/"

[[tutorial]]
name = "Lorem"
weight = 10
identifier = "lorem"
url = "/tutorial/lorem/"


[[main]]
name = "My Articles"
url = "/post/"
weight = 30
identifier = "articles"


[[main]]
name = "Enterprise Strategies"
url = "/categories/enterprise-strategies/"
weight = 10
parent = "articles"

[[main]]
name = "Data Platforms"
url = "/categories/data-platforms/"
weight = 20
parent = "articles"

[[main]]
name = "Platform Engineering"
url = "/categories/platform-engineering/"
weight = 30
parent = "articles"


[[main]]
name = "Techno Bytes"
url = "/categories/techno-bytes/"
weight = 40
parent = "articles"

[[main]]
name = "My Reflections"
url = "/categories/reflections/"
weight = 50

[[main]]
name = "My Experiments"
url = "/experiments/intro/getting-started/"
weight = 60

[[main]]
name = "About"
url = "/about/"
weight = 40

[[main]]
name = "Contact"
url = "/contact/"
weight = 50


[[social]]
name = "X"
pre = '<svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-brand-x" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"></path><path d="M4 4l11.733 16h4.267l-11.733 -16z"></path><path d="M4 20l6.768 -6.768m2.46 -2.46l6.772 -6.772"></path></svg>'
url = "http://x.com/sivadotblog"
weight = 10

[[social]]
name = "LinkedIn"
pre = '<svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-brand-linkedin" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"></path><path d="M4 4m0 2a2 2 0 0 1 2 -2h12a2 2 0 0 1 2 2v12a2 2 0 0 1 -2 2h-12a2 2 0 0 1 -2 -2z"></path><path d="M8 11l0 5"></path><path d="M8 8l0 .01"></path><path d="M12 16l0 -5"></path><path d="M16 16v-3a2 2 0 0 0 -4 0"></path></svg>'
url = "https://www.linkedin.com/in/sivanandhasr/"
weight = 20

[[social]]
name = "GitHub"
pre = '<svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-brand-github" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"></path><path d="M9 19c-4.3 1.4 -4.3 -2.5 -6 -3m12 5v-3.5c0 -1 .1 -1.4 -.5 -2c2.8 -.3 5.5 -1.4 5.5 -6a4.6 4.6 0 0 0 -1.3 -3.2a4.2 4.2 0 0 0 -.1 -3.2s-1.1 -.3 -3.5 1.3a12.3 12.3 0 0 0 -6.2 0c-2.4 -1.6 -3.5 -1.3 -3.5 -1.3a4.2 4.2 0 0 0 -.1 3.2a4.6 4.6 0 0 0 -1.3 3.2c0 4.6 2.7 5.7 5.5 6c-.6 .6 -.6 1.2 -.5 2v3.5"></path></svg>'
url = "https://github.com/sivadotblog/"
weight = 30

# [[sidebar_docs]]
#   name = "Guides"
#   pageRef = "/docs/guides"
#   weight = 10
#
# [[sidebar_docs]]
#   name = "Reference"
#   pageRef = "/docs/reference"
#   weight = 20
#
# [[sidebar_docs]]
#   name = "Resources"
#   pageRef = "/docs/resources"
#   weight = 30

[[footer]]
name = "Privacy Policy"
url = "/privacy/"
weight = 10

# [[footer]]
#   name = "Terms of Service"
#   url = "/terms/"
#   weight = 20
